### ISSUE TITLE
Nicks or aliases containing regex special characters sometimes can't be identified in #action statements

### ISSUE THREAD

**Issue by pronovic** [pronovic/hcoop-meetbot#22]
If you use a nick or assign an alias that contains any regular expression special characters, it may not always be possible to identify actions associated with that nick.  For instance, a nick `k[n` generally can be identified, but not `[ken` or `ken]` or `[ken]`.  This is because the special characters `[` or `]` occur on a regular expression word boundary.  

For the time being, the only workaround is to have participants set a simpler alias that is easier to identify (i.e. nick `[m]` use `#here m`).  However, we do need a longer-term fix, since we learned in issue #20 that nicks that come over through the Matrix IRC bridge often have the form `[m]`.  

I wanted to release v0.5.2 with an immediate bug fix for issue #20, and it didn't seem like there was a quick fix for this problem, so I didn't try to address it in PR #21.  I am not sure whether I can fix this with a more sophisticated regular expression, or whether I need to build some sort of tokenization mechanism and look for matches in a tokenized string.   Either way, I think that I need to refactor out the matching logic used by [`_attendee_actions()`](https://github.com/pronovic/hcoop-meetbot/blob/fc4bf468aa5bd427f2301e6a1edaea00e4770270/src/hcoopmeetbotlogic/writer.py#L220), so it can be unit tested more completely without having to do a bunch of setup logic for a meeting.

**Comment by danshearer** [comment]
You could encourage this, while also encouraging nicer output, by printing this line at the beginning of every meeting: "It is a good idea for each participant to say '#here SingleHumanName', for example '#here Sally' or '#here SallyNguyen'' 

I say 'SingleHumanName' because I once told the MeetBot '#here Dan Shearer' and minor confusion ensued.

**Comment by pronovic** [comment]
Just a note that I would have expected `#here Dan Shearer` to work, because I thought I had unit tests covering that case.  So, I will also work on reproducing that problematic behavior - possibly tracked in a different issue.

**Comment by pronovic** [comment]
@danshearer , I've made some more improvements in the code and fixed this bug in PR #24 .   I also updated the documentation to clarify the expected behavior.  I can't 100% guarantee that the code will identify all action assignments, because the nick or alias still needs to be unambiguous in the action text, and there are plenty of situations where there is some ambiguity.  However, I have greatly improved the range of situations where a match will be properly identified.  

I also looked into the potential problem you raised with aliases containing whitespace (like `#here Dan Shearer`).  I do have a test case covering that situation, and the parser does seem to identify the alias and assign the action appropriately.  Both nicks and aliases are matched case-insensitively (like IRC itself), so that might figure into your situation.  I have updated the documentation to clarify the expected behavior, and added a suggestion to use camel-case for aliases where possible (i.e. `DanShearer` instead of `Dan Shearer`).   If you can reproduce that minor confusion that you referenced above, open a new issue with some details and I'll fix it.

I'll reply here and close this issue once I've released v0.5.3 to PyPI.

**Comment by pronovic** [comment]
Correction: this will be released in v0.6.0

**Comment by pronovic** [comment]
v0.6.0 has been released to PyPI: https://pypi.org/project/hcoop-meetbot/0.6.0/

**Comment by danshearer** [comment]
> I also looked into the potential problem you raised with aliases containing whitespace (like `#here Dan Shearer`). 

@pronovic this was a false alert, apologies. I confused the bug where certain characters in aliases causing partial logs and other strange behaviour with missing action items arising from mis-specifying the nick.

If there are spaces in nicks (which you have now suggested in the documentation and banner may not be best practice), I have made a user error several times. Someone identified themselves with "#here First Läst",  but I later incorrectly wrote "#action First" instead of "#action First Läst". This user error supports your mild deprecation of the practice, because it's an easy mistake to make.

Dan

**Comment by danshearer** [comment]
Perhaps you would not prefer me to re-open issues to give you feedback? There is also a discussion forum feature in GitHub, although that seems a little amusing given your bot is for a discussion network.

**Comment by pronovic** [comment]
Commenting on a closed issue does not seem to reopen it, so it seems fine to me that you comment on the issue the way you have been doing.
