### ISSUE TITLE
Feature request: mechanism to parse a raw log and regenerate the HTML files

### ISSUE THREAD

**Issue by pronovic** [pronovic/hcoop-meetbot#23]
This is something that the original MeetBot plugin had, but I haven't yet built.  If the plugin crashes (as in issue #20), then the minutes don't get generated, and there's really no recourse.   It would nice to provide some sort of mechanism to take the raw log and generate the minutes from it.  That wouldn't necessarily solve all problems, but would at least provide a workaround if there's a bug that prevents the minutes from being generated.

**Comment by pronovic** [comment]
Part of the complexity here is that I don't save off the raw log on disk, only the HTML-formatted log.  So, I don't necessarily have all of the context needed to regenerate the minutes - or rather, most of it is probably there, but would have to be parsed out of the HTML log, which is really not ideal.  I need to come up with a mechanism to serialize and deserialize a `Meeting` object, which would let me re-use the existing code like `MeetingMinutes.for_meeting(config, meeting)`.  I'll also look at doing some refactoring to better support multiple output formats in the future (such as Markdown), although i won't actually be implementing that now.

**Comment by pronovic** [comment]
This will be complete once I merge PR #26.  v0.5.3 will generate a raw JSON log for every meeting, and also includes a new  `meetbot` CLI tool with a `regenerate` utility.  The `regenerate` utility uses the JSON log file as input, and regenerates formatted output based on configuration.  You can use this to work around a bug, take advantage of improved output in future releases, or switch to a new output format (if/when I support some format other than HTML).  Of course, this will only work for meetings run with v0.5.3 or greater, but at least it gives you some additional flexibility moving forward.  I'll close this issue when I publish v0.5.3 to PyPI.

**Comment by pronovic** [comment]
Correction: this will be released as v0.6.0

**Comment by pronovic** [comment]
v0.6.0 has been released to PyPI: https://pypi.org/project/hcoop-meetbot/0.6.0/

**Comment by danshearer** [comment]
idk if this is the place to report, however, I can confirm that the command `meetbot regenerate -c lumosql-meetbot.conf -r meetings/Team_Catchup.20220610.0803.log.json -d /tmp` generates the same two files in /tmp as it generated from the meeting. This appears to work perfectly, and thankyou very much Kenneth.

**Comment by pronovic** [comment]
Thanks for confirming @danshearer
